// Code generated by generate-docs; DO NOT EDIT.

export type EventReason = 'bulk-replay' | 'live-event' | 'single-replay'

export type SocketMessage<TType extends string, TFields> = {
  event_id: string
  fields: TFields
  is_live: boolean
  reason: EventReason
  time: Date
  type: TType
}


export type AdbreakBeginFields = {
  /** Channel the event occurred in */
  channel: string
  /** Duration of the ad break in seconds */
  duration: number
  /** Whether the ad break was started automatically */
  is_automatic: boolean
  /** Time the ad break started */
  started_at: string
}

export type AdbreakBeginSocketMessage = SocketMessage<'adbreak_begin', AdbreakBeginFields>

export type AnnouncementFields = {
  /** Channel the event occurred in */
  channel: string
  /** Announcement color */
  color: string
  /** Announcement text */
  message: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type AnnouncementSocketMessage = SocketMessage<'announcement', AnnouncementFields>

export type BanFields = {
  /** Channel the event occurred in */
  channel: string
  /** ID of the user being banned */
  target_id: string
  /** Login name of the user being banned */
  target_name: string
}

export type BanSocketMessage = SocketMessage<'ban', BanFields>

export type BitsFields = {
  /** Total amount of bits spent in the message */
  bits: number
  /** Channel the event occurred in */
  channel: string
  /** Chat message containing the bits */
  message: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type BitsSocketMessage = SocketMessage<'bits', BitsFields>

export type CategoryUpdateFields = {
  /** New stream category */
  category: string
  /** Channel the event occurred in */
  channel: string
}

export type CategoryUpdateSocketMessage = SocketMessage<'category_update', CategoryUpdateFields>

export type ChannelpointRedeemFields = {
  /** Channel the event occurred in */
  channel: string
  /** Number of points paid for the reward */
  reward_cost: number
  /** ID of the redeemed reward */
  reward_id: string
  /** Title of the redeemed reward */
  reward_title: string
  /** Status of the redemption */
  status: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
  /** Text entered for the reward */
  user_input: string
}

export type ChannelpointRedeemSocketMessage = SocketMessage<'channelpoint_redeem', ChannelpointRedeemFields>

export type ClearchatFields = {
  /** Channel the event occurred in */
  channel: string
}

export type ClearchatSocketMessage = SocketMessage<'clearchat', ClearchatFields>

export type CustomFields = Record<string, unknown> & { channel: string }

export type CustomSocketMessage = SocketMessage<'custom', CustomFields>

export type DeleteFields = {
  /** Channel the event occurred in */
  channel: string
  /** UUID of the message being deleted */
  message_id: string
  /** Login name of the author of the deleted message */
  target_name: string
}

export type DeleteSocketMessage = SocketMessage<'delete', DeleteFields>

export type FollowFields = {
  /** Channel the event occurred in */
  channel: string
  /** Time the user followed the channel */
  followed_at: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type FollowSocketMessage = SocketMessage<'follow', FollowFields>

export type GiftpaidupgradeFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who gifted the subscription */
  gifter: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type GiftpaidupgradeSocketMessage = SocketMessage<'giftpaidupgrade', GiftpaidupgradeFields>

export type HypetrainBeginFields = {
  /** Channel the event occurred in */
  channel: string
  /** Raw Hype-Train event */
  event: unknown
  /** Current Hype-Train level */
  level: number
  /** Progress towards the next Hype-Train level */
  levelProgress: number
}

export type HypetrainBeginSocketMessage = SocketMessage<'hypetrain_begin', HypetrainBeginFields>

export type HypetrainEndFields = {
  /** Channel the event occurred in */
  channel: string
  /** Raw Hype-Train event */
  event: unknown
  /** Current Hype-Train level */
  level: number
}

export type HypetrainEndSocketMessage = SocketMessage<'hypetrain_end', HypetrainEndFields>

export type HypetrainProgressFields = {
  /** Channel the event occurred in */
  channel: string
  /** Raw Hype-Train event */
  event: unknown
  /** Current Hype-Train level */
  level: number
  /** Progress towards the next Hype-Train level */
  levelProgress: number
}

export type HypetrainProgressSocketMessage = SocketMessage<'hypetrain_progress', HypetrainProgressFields>

export type JoinFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type JoinSocketMessage = SocketMessage<'join', JoinFields>

export type KofiDonationFields = {
  /** Amount donated as submitted by Ko-fi */
  amount: number
  /** Channel the event occurred for */
  channel: string
  /** Currency of the donated amount */
  currency: string
  /** Name submitted by the donor */
  from: string
  /** Whether this is the first subscription payment */
  isFirstSubPayment: boolean
  /** Whether this is a subscription payment */
  isSubscription: boolean
  /** Message entered by the donor */
  message?: string
  /** Subscription tier */
  tier?: string
}

export type KofiDonationSocketMessage = SocketMessage<'kofi_donation', KofiDonationFields>

export type ModeratorAddFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type ModeratorAddSocketMessage = SocketMessage<'moderator_add', ModeratorAddFields>

export type ModeratorRemoveFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type ModeratorRemoveSocketMessage = SocketMessage<'moderator_remove', ModeratorRemoveFields>

export type OutboundRaidFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the channel receiving the raid */
  to: string
  /** ID of the channel receiving the raid */
  to_id: string
  /** Number of viewers included in the raid */
  viewers: number
}

export type OutboundRaidSocketMessage = SocketMessage<'outbound_raid', OutboundRaidFields>

export type PartFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type PartSocketMessage = SocketMessage<'part', PartFields>

export type PermitFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who received the permit */
  to: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type PermitSocketMessage = SocketMessage<'permit', PermitFields>

export type PollBeginFields = {
  /** Channel the event occurred in */
  channel: string
  /** Whether channel-point voting is enabled */
  hasChannelPointVoting: boolean
  /** Raw poll event */
  poll: unknown
  /** Poll title */
  title: string
}

export type PollBeginSocketMessage = SocketMessage<'poll_begin', PollBeginFields>

export type PollEndFields = {
  /** Channel the event occurred in */
  channel: string
  /** Whether channel-point voting is enabled */
  hasChannelPointVoting: boolean
  /** Raw poll event */
  poll: unknown
  /** Poll status */
  status: string
  /** Poll title */
  title: string
}

export type PollEndSocketMessage = SocketMessage<'poll_end', PollEndFields>

export type PollProgressFields = {
  /** Channel the event occurred in */
  channel: string
  /** Whether channel-point voting is enabled */
  hasChannelPointVoting: boolean
  /** Raw poll event */
  poll: unknown
  /** Poll title */
  title: string
}

export type PollProgressSocketMessage = SocketMessage<'poll_progress', PollProgressFields>

export type PrimepaidupgradeFields = {
  /** Channel the event occurred in */
  channel: string
  /** Paid subscription plan */
  plan: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type PrimepaidupgradeSocketMessage = SocketMessage<'primepaidupgrade', PrimepaidupgradeFields>

export type RaidFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who raided the channel */
  from: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
  /** Number of viewers included in the raid */
  viewercount: number
}

export type RaidSocketMessage = SocketMessage<'raid', RaidFields>

export type ResubFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who resubscribed */
  from: string
  /** Message shared with the resubscription */
  message: string
  /** Multi-month duration in months reported by Twitch */
  multi_month: number
  /** Subscription plan */
  plan: string
  /** Number of months the user has been subscribed */
  subscribed_months: number
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type ResubSocketMessage = SocketMessage<'resub', ResubFields>

export type ShoutoutCreatedFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the channel receiving the shoutout */
  to: string
  /** ID of the channel receiving the shoutout */
  to_id: string
  /** Number of viewers shown the shoutout */
  viewers: number
}

export type ShoutoutCreatedSocketMessage = SocketMessage<'shoutout_created', ShoutoutCreatedFields>

export type ShoutoutReceivedFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the channel issuing the shoutout */
  from: string
  /** ID of the channel issuing the shoutout */
  from_id: string
  /** Number of viewers shown the shoutout */
  viewers: number
}

export type ShoutoutReceivedSocketMessage = SocketMessage<'shoutout_received', ShoutoutReceivedFields>

export type StreamOfflineFields = {
  /** Channel the event occurred in */
  channel: string
}

export type StreamOfflineSocketMessage = SocketMessage<'stream_offline', StreamOfflineFields>

export type StreamOnlineFields = {
  /** Channel the event occurred in */
  channel: string
}

export type StreamOnlineSocketMessage = SocketMessage<'stream_online', StreamOnlineFields>

export type SubFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who subscribed */
  from: string
  /** Multi-month duration in months reported by Twitch */
  multi_month: number
  /** Subscription plan */
  plan: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type SubSocketMessage = SocketMessage<'sub', SubFields>

export type SubgiftFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who gifted the subscription */
  from: string
  /** Number of months the user gifted */
  gifted_months: number
  /** Multi-month duration in months reported by Twitch */
  multi_month: number
  /** ID unique to the gift event */
  origin_id: string
  /** Subscription plan */
  plan: string
  /** Number of months the recipient has been subscribed */
  subscribed_months: number
  /** Login name of the user who received the subscription */
  to: string
  /** Total number of subscriptions gifted by the user */
  total_gifted: number
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type SubgiftSocketMessage = SocketMessage<'subgift', SubgiftFields>

export type SubmysterygiftFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user who gifted the subscriptions */
  from: string
  /** Multi-month duration in months reported by Twitch */
  multi_month: number
  /** Number of gifted subscriptions */
  number: number
  /** ID unique to the gift event */
  origin_id: string
  /** Subscription plan */
  plan: string
  /** Total number of subscriptions gifted by the user */
  total_gifted: number
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type SubmysterygiftSocketMessage = SocketMessage<'submysterygift', SubmysterygiftFields>

export type SusUserMessageFields = {
  /** Ban-evasion evaluation */
  ban_evasion: string
  /** Channel the event occurred in */
  channel: string
  /** Message text */
  message: string
  /** IDs of shared-ban channels */
  shared_ban_channels: Array<string>
  /** Restriction status */
  status: string
  /** ID of the suspicious user */
  user_id: string
  /** Suspicious-user types */
  user_type: Array<string>
  /** Login name of the suspicious user */
  username: string
}

export type SusUserMessageSocketMessage = SocketMessage<'sus_user_message', SusUserMessageFields>

export type SusUserUpdateFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the acting moderator */
  moderator: string
  /** Restriction status */
  status: string
  /** ID of the suspicious user */
  user_id: string
  /** Login name of the suspicious user */
  username: string
}

export type SusUserUpdateSocketMessage = SocketMessage<'sus_user_update', SusUserUpdateFields>

export type TimeoutFields = {
  /** Channel the event occurred in */
  channel: string
  /** Timeout duration in nanoseconds */
  duration: number
  /** Timeout duration in seconds */
  seconds: number
  /** ID of the user being timed out */
  target_id: string
  /** Login name of the user being timed out */
  target_name: string
}

export type TimeoutSocketMessage = SocketMessage<'timeout', TimeoutFields>

export type TitleUpdateFields = {
  /** Channel the event occurred in */
  channel: string
  /** New stream title */
  title: string
}

export type TitleUpdateSocketMessage = SocketMessage<'title_update', TitleUpdateFields>

export type VipAddFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type VipAddSocketMessage = SocketMessage<'vip_add', VipAddFields>

export type VipRemoveFields = {
  /** Channel the event occurred in */
  channel: string
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type VipRemoveSocketMessage = SocketMessage<'vip_remove', VipRemoveFields>

export type WatchStreakFields = {
  /** Channel the event occurred in */
  channel: string
  /** Message shared with the milestone */
  message: string
  /** Watch-streak value */
  streak: number
  /** Login name of the user associated with the event */
  user: string
  /** ID of the user associated with the event */
  user_id?: string
}

export type WatchStreakSocketMessage = SocketMessage<'watch_streak', WatchStreakFields>

export type WhisperFields = {
}

export type WhisperSocketMessage = SocketMessage<'whisper', null>

export type EventSocketMessage = AdbreakBeginSocketMessage | AnnouncementSocketMessage | BanSocketMessage | BitsSocketMessage | CategoryUpdateSocketMessage | ChannelpointRedeemSocketMessage | ClearchatSocketMessage | CustomSocketMessage | DeleteSocketMessage | FollowSocketMessage | GiftpaidupgradeSocketMessage | HypetrainBeginSocketMessage | HypetrainEndSocketMessage | HypetrainProgressSocketMessage | JoinSocketMessage | KofiDonationSocketMessage | ModeratorAddSocketMessage | ModeratorRemoveSocketMessage | OutboundRaidSocketMessage | PartSocketMessage | PermitSocketMessage | PollBeginSocketMessage | PollEndSocketMessage | PollProgressSocketMessage | PrimepaidupgradeSocketMessage | RaidSocketMessage | ResubSocketMessage | ShoutoutCreatedSocketMessage | ShoutoutReceivedSocketMessage | StreamOfflineSocketMessage | StreamOnlineSocketMessage | SubSocketMessage | SubgiftSocketMessage | SubmysterygiftSocketMessage | SusUserMessageSocketMessage | SusUserUpdateSocketMessage | TimeoutSocketMessage | TitleUpdateSocketMessage | VipAddSocketMessage | VipRemoveSocketMessage | WatchStreakSocketMessage | WhisperSocketMessage

export type EventHandlers = {
  [TType in EventSocketMessage['type']]?: (
    event: Extract<EventSocketMessage, { type: TType }>,
  ) => unknown
} & {
  _?: (event: EventSocketMessage) => unknown
}
