name: CI Workflow

on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:d52fa88257f5f2f107e8f3c452b677dc7fc96edde2aace4d5606f92280ea8c14
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Lint and test code
        run: make lint test frontend_lint

      - name: Build release (quick local for compile)
        run: make build_prod

      - name: Execute Trivy scan
        run: make trivy
