---

if: ${{ github.ref == 'refs/heads/master' }}
needs: [test]

defaults:
  run:
    shell: bash

container:
  image: luzifer/gh-arch-env
  env:
    CGO_ENABLED: 0
    GOPATH: /go

runs-on: ubuntu-latest

services:
  postgres:
    image: postgres:15
    env:
      POSTGRES_PASSWORD: twitch-bot-pass
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

steps:
  - uses: actions/checkout@v4
    with:
      show-progress: false

  - name: Marking workdir safe
    run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

  - name: Run tests against PostgreSQL
    env:
      GO_TEST_DB_ENGINE: postgres
      GO_TEST_DB_DSN: host=postgres user=postgres password=twitch-bot-pass dbname=postgres port=5432 sslmode=disable timezone=UTC
    run: make short_test

...
