---

if: ${{ github.ref == 'refs/heads/master' }}
needs: [test]

defaults:
  run:
    shell: bash

container:
  image: luzifer/gh-arch-env
  env:
    CGO_ENABLED: 0
    GOPATH: /go

runs-on: ubuntu-latest

services:
  mysql:
    image: mysql:8
    env:
      MYSQL_PASSWORD: twitch-bot-pass
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_USER: twitch-bot
    options: >-
      --health-cmd "mysqladmin ping"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

steps:
  - name: Install required packages
    run: |
      pacman -Syy --noconfirm \
        mariadb-clients

  - uses: actions/checkout@v4
    with:
      show-progress: false

  - name: Marking workdir safe
    run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

  - name: Set up MySQL service
    run: |
      mariadb -h mysql -u root --password=root-pass <<EOF
      CREATE DATABASE integration DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
      GRANT ALL ON integration.* TO 'twitch-bot'@'%';
      EOF

  - name: Run tests against MySQL
    env:
      GO_TEST_DB_ENGINE: mysql
      GO_TEST_DB_DSN: twitch-bot:twitch-bot-pass@tcp(mysql:3306)/integration?charset=utf8mb4&parseTime=True
    run: make short_test

...
