---

name: doc-generator
on: push

jobs:
  doc-generator:
    defaults:
      run:
        shell: bash

    container:
      image: luzifer/archlinux
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:

      - name: Install required packages
        run: |
          pacman -Syy --noconfirm \
            curl \
            git \
            make \
            tar

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Generate documentation
        run: make render_docs

      - name: Upload GitHub Pages artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: .rendered-docs

      - name: Deploy artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v1

...
