---

name: wiki-update
on:
  push:
    branches:
      - master

jobs:
  wiki-update:
    defaults:
      run:
        shell: bash

    container:
      image: luzifer/archlinux
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:

      - name: Install required packages
        run: |
          pacman -Syy --noconfirm \
            git

      - uses: actions/checkout@v3

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Update Wiki
        run: 'git push https://github.com/Luzifer/twitch-bot.wiki.git $(git subtree split --prefix wiki HEAD):refs/heads/master --force'

...
