name: CI Workflow

on: push

permissions:
  contents: read

jobs:
  test:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:be28a4950f1854aa38987bd05154f0a135841fdd17b13d04f8af59f240ff83d8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Lint and test code
        run: make lint test frontend_lint

      - name: Build release (quick local for compile)
        run: make build_prod

      - name: Execute Trivy scan
        run: make trivy

  doc-generator:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' }}
    needs: [test]

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
          submodules: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ghcr.io/luzifer/twitch-bot-docs

      - name: Log into registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ./docs
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-publish:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' }}
    needs: [test]

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ghcr.io/luzifer/twitch-bot

      - name: Log into registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  integration-mariadb:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [test]

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:be28a4950f1854aa38987bd05154f0a135841fdd17b13d04f8af59f240ff83d8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:12.3.2@sha256:b1c7bf836e64ed9406a8984af29509f40089d55cea14b32f12c4726a1f17104b
        env:
          MYSQL_PASSWORD: twitch-bot-pass
          MYSQL_ROOT_PASSWORD: root-pass
          MYSQL_USER: twitch-bot
        options: >-
          --health-cmd "healthcheck.sh
          --connect
          --innodb_initialized"
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    steps:
      - name: Install required packages
        run: apt-get install -y --no-install-recommends mariadb-client

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Set up MariaDB service
        run: |
          mariadb -h mariadb -u root --password=root-pass <<EOF
            CREATE DATABASE integration DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
            GRANT ALL ON integration.* TO 'twitch-bot'@'%';
          EOF

      - name: Run tests against MariaDB
        env:
          GO_TEST_DB_ENGINE: mysql
          GO_TEST_DB_DSN: twitch-bot:twitch-bot-pass@tcp(mariadb:3306)/integration?charset=utf8mb4&parseTime=True
        run: make short_test

  integration-mysql:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [test]

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:be28a4950f1854aa38987bd05154f0a135841fdd17b13d04f8af59f240ff83d8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:9.7.1@sha256:ad88e1c86cbf12ef52d0a0360cd4b774d22956c5ee9c565645fb019d7aacb6c3
        env:
          MYSQL_PASSWORD: twitch-bot-pass
          MYSQL_ROOT_PASSWORD: root-pass
          MYSQL_USER: twitch-bot
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    steps:
      - name: Install required packages
        run: apt-get install -y --no-install-recommends mariadb-client

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Set up MySQL service
        run: |
          mariadb --skip-ssl -h mysql -u root --password=root-pass <<EOF
            CREATE DATABASE integration DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
            GRANT ALL ON integration.* TO 'twitch-bot'@'%';
          EOF

      - name: Run tests against MySQL
        env:
          GO_TEST_DB_ENGINE: mysql
          GO_TEST_DB_DSN: twitch-bot:twitch-bot-pass@tcp(mysql:3306)/integration?charset=utf8mb4&parseTime=True
        run: make short_test

  integration-postgres:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [test]

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:be28a4950f1854aa38987bd05154f0a135841fdd17b13d04f8af59f240ff83d8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.4@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
        env:
          POSTGRES_PASSWORD: twitch-bot-pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Run tests against PostgreSQL
        env:
          GO_TEST_DB_ENGINE: postgres
          GO_TEST_DB_DSN: >
            host=postgres
            user=postgres
            password=twitch-bot-pass
            dbname=postgres
            port=5432
            sslmode=disable
            timezone=UTC
        run: make short_test

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: [test]

    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:be28a4950f1854aa38987bd05154f0a135841fdd17b13d04f8af59f240ff83d8
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/twitch-bot/twitch-bot

      - name: Build release
        run: make publish

      - name: Extract changelog
        run: awk "/^#/ && ++c==2{exit}; /^#/f" "History.md" | tail -n +2 >release_changelog.md

      - name: Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          artifacts: .build/*
          bodyFile: release_changelog.md
          draft: false
          generateReleaseNotes: false
